### ISSUE TITLE
06-order-statistics

### ISSUE THREAD

**Issue by Megan-Hollister** [wadem117/Probability-and-Inference-Portfolio-Wade-Michael-#5]
I cannot see code for the last 3 questions. Also there is very little explanation throughout.

**Comment by Megan-Hollister** [comment]
Very little explanation throughout. Please resubmit.

**Comment by Megan-Hollister** [comment]
I like the explanations. Skipped questions:
"Use the newly modified functions to plot the probability and density functions for the sample **min** (N = 200)."

"Generate the QQ plot for simulated data from the sampling distribution of the sample **max** and the theoretical largest order statistic distribution."

**Comment by wadem117** [comment]
Just updated!

**Comment by Megan-Hollister** [comment]
PASS
